return {
  reactor = "fissionReactorLogicAdapter_0",
  debug = false,
  maxDamage = 0,
  first_start = false,
  minFuel = 0.1,
  update = true,
  maxWaste = 0.9,
  monitor = "monitor_1",
  maxTemperature = 950,
  cardKey = "1111",
  pin = "1111",
  refreshRate = 0,
  minCoolant = 0.2,
}